name: GitHub Actions Dependency Submission
description:
  Submits GitHub Actions dependencies from workflow files to the Dependency
  Submission API
author: Jesse Houwing

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: check-circle
  color: blue

# Define your inputs here.
inputs:
  token:
    description:
      'GitHub Personal Access Token (PAT). Defaults to PAT provided by Action
      runner'
    required: false
    default: ${{ github.token }}
  workflow-path:
    description:
      'Path to the .github/workflows directory. Defaults to .github/workflows'
    required: false
    default: '.github/workflows'

# Define your outputs here.
outputs:
  snapshot-id:
    description: 'The ID of the submitted dependency snapshot'

runs:
  using: node24
  main: dist/index.js
